### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to resourceEnvironments for identityGovernance
module: Microsoft.Graph.Identity.Governance
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphAccessPackageResourceEnvironment>`: accessPackageResourceEnvironment
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[CreatedDateTime <DateTime?>]`: 
    - `[Description <String>]`: 
    - `[DisplayName <String>]`: 
    - `[IsDefaultEnvironment <Boolean?>]`: 
    - `[ModifiedDateTime <DateTime?>]`: 
    - `[OriginId <String>]`: 
    - `[OriginSystem <String>]`: 
    - `[Resources <IMicrosoftGraphAccessPackageResource[]>]`: 
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[CreatedDateTime <DateTime?>]`: 
      - `[Description <String>]`: 
      - `[DisplayName <String>]`: 
      - `[Environment <IMicrosoftGraphAccessPackageResourceEnvironment>]`: accessPackageResourceEnvironment
      - `[ModifiedDateTime <DateTime?>]`: 
      - `[OriginId <String>]`: 
      - `[OriginSystem <String>]`: 
      - `[Roles <IMicrosoftGraphAccessPackageResourceRole[]>]`: 
        - `[Id <String>]`: The unique idenfier for an entity. Read-only.
        - `[Description <String>]`: 
        - `[DisplayName <String>]`: 
        - `[OriginId <String>]`: 
        - `[OriginSystem <String>]`: 
        - `[Resource <IMicrosoftGraphAccessPackageResource>]`: accessPackageResource
      - `[Scopes <IMicrosoftGraphAccessPackageResourceScope[]>]`: 
        - `[Id <String>]`: The unique idenfier for an entity. Read-only.
        - `[Description <String>]`: 
        - `[DisplayName <String>]`: 
        - `[IsRootScope <Boolean?>]`: 
        - `[OriginId <String>]`: 
        - `[OriginSystem <String>]`: 
        - `[Resource <IMicrosoftGraphAccessPackageResource>]`: accessPackageResource

  `RESOURCES <IMicrosoftGraphAccessPackageResource[]>`: .
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[CreatedDateTime <DateTime?>]`: 
    - `[Description <String>]`: 
    - `[DisplayName <String>]`: 
    - `[Environment <IMicrosoftGraphAccessPackageResourceEnvironment>]`: accessPackageResourceEnvironment
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[CreatedDateTime <DateTime?>]`: 
      - `[Description <String>]`: 
      - `[DisplayName <String>]`: 
      - `[IsDefaultEnvironment <Boolean?>]`: 
      - `[ModifiedDateTime <DateTime?>]`: 
      - `[OriginId <String>]`: 
      - `[OriginSystem <String>]`: 
      - `[Resources <IMicrosoftGraphAccessPackageResource[]>]`: 
    - `[ModifiedDateTime <DateTime?>]`: 
    - `[OriginId <String>]`: 
    - `[OriginSystem <String>]`: 
    - `[Roles <IMicrosoftGraphAccessPackageResourceRole[]>]`: 
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[Description <String>]`: 
      - `[DisplayName <String>]`: 
      - `[OriginId <String>]`: 
      - `[OriginSystem <String>]`: 
      - `[Resource <IMicrosoftGraphAccessPackageResource>]`: accessPackageResource
    - `[Scopes <IMicrosoftGraphAccessPackageResourceScope[]>]`: 
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[Description <String>]`: 
      - `[DisplayName <String>]`: 
      - `[IsRootScope <Boolean?>]`: 
      - `[OriginId <String>]`: 
      - `[OriginSystem <String>]`: 
      - `[Resource <IMicrosoftGraphAccessPackageResource>]`: accessPackageResource
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAccessPackageResourceEnvironment" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAccessPackageResourceEnvironment" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-MgEntitlementManagementResourceEnvironment [-AdditionalProperties <Hashtable>]

   [-CreatedDateTime <DateTime>] [-Description <String>] [-DisplayName <String>] [-Id <String>]

   [-IsDefaultEnvironment] [-ModifiedDateTime <DateTime>] [-OriginId <String>] [-OriginSystem <String>]

   [-Resources <IMicrosoftGraphAccessPackageResource[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgEntitlementManagementResourceEnvironment -BodyParameter <IMicrosoftGraphAccessPackageResourceEnvironment>

   [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphAccessPackageResourceEnvironment" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    accessPackageResourceEnvironment
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CreatedDateTime
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique idenfier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsDefaultEnvironment
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: ModifiedDateTime
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OriginId
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OriginSystem
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphAccessPackageResource" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Resources
  description: |+
    .
    To construct, see NOTES section for RESOURCES properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Identity.Governance.New-MgEntitlementManagementResourceEnvironment
name: New-MgEntitlementManagementResourceEnvironment
description: |-
  Create new navigation property to resourceEnvironments for identityGovernance
metadata:
  external help file: Microsoft.Graph.Identity.Governance-help.xml
  Module Name: Microsoft.Graph.Identity.Governance
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.identity.governance/new-mgentitlementmanagementresourceenvironment
  schema: 2.0.0
