steps:  
# - checkout: msgraph-sdk-powershell
#   clean: true
#   fetchDepth: 1
#   submodules: true
#   persistCredentials: true
  
- checkout: self
  clean: true
  fetchDepth: 1
  submodules: true
  persistCredentials: true
  